//! This build script simply generates C FFI bindings for the freestanding
//! functions in `lib.rs` and dumps them into a header that the Dolphin
//! project is pre-configured to find.

use std::env;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    // We disable `enum class` declarations to mirror what Ishiiruka
    // currently does.
    let enum_config = cbindgen::EnumConfig {
        enum_class: false,
        ..Default::default()
    };

    let warning = "/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */";

    let config = cbindgen::Config {
        autogen_warning: Some(warning.into()),
        cpp_compat: true,
        enumeration: enum_config,
        language: cbindgen::Language::C,
        pragma_once: true,
        ..Default::default()
    };

    cbindgen::Builder::new()
        .with_config(config)
        .with_crate(crate_dir)
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file("includes/SlippiRustExtensions.h");
}
