#pragma once

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Size in bytes of the buffer `slprs_stun_build_request` fills.
 */
#define SLPRS_STUN_REQUEST_LEN 20

/**
 * Indicates what type of direct code operation we're in.
 */
typedef enum DirectCodeKind {
  DirectCodes = 1,
  TeamsCodes = 2,
} DirectCodeKind;

/**
 * This enum is duplicated from `slippi_game_reporter::OnlinePlayMode` in order
 * to appease cbindgen, which cannot see the type from the other module for
 * inspection.
 *
 * This enum will likely go away as things move towards Rust, since it's effectively
 * just C FFI glue code.
 */
typedef enum SlippiMatchmakingOnlinePlayMode {
  Ranked = 0,
  Unranked = 1,
  Direct = 2,
  Teams = 3,
} SlippiMatchmakingOnlinePlayMode;

/**
 * A configuration struct for passing over certain argument types from the C/C++ side.
 *
 * The number of arguments necessary to shuttle across the FFI boundary when starting the
 * EXI device is higher than ideal at the moment, though it should lessen with time. For now,
 * this struct exists to act as a slightly more sane approach to readability of the args
 * structure.
 */
typedef struct SlippiRustEXIConfig {
  const char *iso_path;
  const char *user_config_folder;
  const char *scm_slippi_semver_str;
  void (*osd_add_msg_fn)(const char*, uint32_t, uint32_t);
} SlippiRustEXIConfig;

/**
 * ISO MD5 status and final outcome that we vend back over FFI.
 */
typedef struct RustIsoMd5Check {
  /**
   * 0 = NotStarted, 1 = InProgress, 2 = Complete
   */
  int status;
  /**
   * 0 = Unknown, 1 = SafeIso, 2 = KnownDesyncIso, 3 = Failed
   */
  int result;
} RustIsoMd5Check;

/**
 * What one STUN server reported for the netplay socket. Filled in by
 * `slprs_stun_parse_response`; leave it zeroed for a server that did not
 * answer.
 */
typedef struct SlippiStunObservation {
  /**
   * False when the server did not answer, in which case the other fields
   * are ignored.
   */
  bool answered;
  /**
   * Public IPv4 address as four octets.
   */
  uint8_t ip[4];
  /**
   * Public port in host order.
   */
  uint16_t port;
} SlippiStunObservation;

/**
 * Everything the Dolphin side knows when it asks for a match. Strings must be
 * valid, possibly empty, C strings; they are copied during the call.
 */
typedef struct SlippiMatchmakingRequest {
  /**
   * 0 ranked, 1 unranked, 2 direct, 3 teams, 4 party.
   */
  uint8_t mode;
  /**
   * Opponent connect code or lobby code as the raw Shift-JIS bytes the
   * game provides. May be null when the length is zero.
   */
  const uint8_t *connect_code;
  uintptr_t connect_code_len;
  /**
   * Local UDP port the ENet host is bound to.
   */
  uint16_t netplay_port;
  /**
   * "ip:port" on the local network, or empty.
   */
  const char *lan_addr;
  /**
   * What each of two STUN servers reported for the netplay socket, in the
   * order they were asked. The NAT is classified from them on this side.
   */
  struct SlippiStunObservation stun[2];
} SlippiMatchmakingRequest;

/**
 * Rank info that we vend back to the Dolphin side of things.
 */
typedef struct RustRankInfo {
  int fetch_status;
  char rank;
  float rating_ordinal;
  unsigned int rating_update_count;
  float rating_change;
  int rank_change;
} RustRankInfo;

/**
 * An intermediary type for moving `UserInfo` across the FFI boundary.
 *
 * This type is C compatible, and we coerce Rust types into C types for this struct to
 * ease passing things over. This must be free'd on the Rust side via `slprs_user_free_info`.
 */
typedef struct RustUserInfo {
  const char *uid;
  const char *play_key;
  const char *display_name;
  const char *connect_code;
  const char *latest_version;
} RustUserInfo;

/**
 * An intermediary type for moving chat messages across the FFI boundary.
 *
 * This type is C compatible, and we coerce Rust types into C types for this struct to
 * ease passing things over. This must be free'd on the Rust side via `slprs_user_free_messages`.
 */
typedef struct RustChatMessages {
  char **data;
  int len;
} RustChatMessages;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Creates and leaks a shadow EXI device with the provided configuration.
 *
 * The C++ (Dolphin) side of things should call this and pass the appropriate arguments. At
 * that point, everything on the Rust side is its own universe, and should be told to shut
 * down (at whatever point) via the corresponding `slprs_exi_device_destroy` function.
 *
 * The returned pointer from this should *not* be used after calling `slprs_exi_device_destroy`.
 */
uintptr_t slprs_exi_device_create(struct SlippiRustEXIConfig config);

/**
 * The C++ (Dolphin) side of things should call this to notify the Rust side that it
 * can safely shut down and clean up.
 */
void slprs_exi_device_destroy(uintptr_t exi_device_instance_ptr);

/**
 * This method should be called from the EXI device subclass shim that's registered on
 * the Dolphin side, corresponding to:
 *
 * `virtual void DMAWrite(u32 _uAddr, u32 _uSize);`
 */
void slprs_exi_device_dma_write(uintptr_t exi_device_instance_ptr,
                                const uint8_t *address,
                                const uint8_t *size);

/**
 * This method should be called from the EXI device subclass shim that's registered on
 * the Dolphin side, corresponding to:
 *
 * `virtual void DMARead(u32 _uAddr, u32 _uSize);`
 */
void slprs_exi_device_dma_read(uintptr_t exi_device_instance_ptr,
                               const uint8_t *address,
                               const uint8_t *size);

/**
 * Moves ownership of the `GameReport` at the specified address to the
 * `SlippiGameReporter` on the EXI Device the corresponding address. This
 * will then add it to the processing pipeline.
 *
 * The reporter will manage the actual... reporting.
 */
void slprs_exi_device_log_game_report(uintptr_t instance_ptr, uintptr_t game_report_instance_ptr);

/**
 * Calls through to `SlippiGameReporter::start_new_session`.
 */
void slprs_exi_device_start_new_reporter_session(uintptr_t instance_ptr);

/**
 * Calls through to the `SlippiGameReporter` on the EXI device to report a
 * match status update event.
 */
void slprs_exi_device_report_match_status(uintptr_t instance_ptr,
                                          const char *match_id,
                                          const char *status,
                                          bool background);

/**
 * Calls through to `SlippiGameReporter::push_replay_data`.
 */
void slprs_exi_device_reporter_push_replay_data(uintptr_t instance_ptr,
                                                const uint8_t *data,
                                                uint32_t length);

/**
 * Gets the status and result of the background ISO MD5 check.
 */
struct RustIsoMd5Check slprs_get_iso_md5_check(uintptr_t exi_device_instance_ptr);

/**
 * Configures the Jukebox process. This needs to be called after the EXI device is created
 * in order for certain pieces of Dolphin to be properly initalized; this may change down
 * the road though and is not set in stone.
 */
void slprs_exi_device_configure_jukebox(uintptr_t exi_device_instance_ptr,
                                        bool is_enabled,
                                        uint8_t initial_dolphin_system_volume,
                                        uint8_t initial_dolphin_music_volume);

/**
 * Creates a new Player Report and leaks it, returning the pointer.
 *
 * This should be passed on to a GameReport for processing.
 */
uintptr_t slprs_player_report_create(const char *uid,
                                     uint8_t slot_type,
                                     double damage_done,
                                     uint8_t stocks_remaining,
                                     uint8_t character_id,
                                     uint8_t color_id,
                                     int64_t starting_stocks,
                                     int64_t starting_percent);

/**
 * Creates a new GameReport and leaks it, returning the instance pointer
 * after doing so.
 *
 * This is expected to ultimately be passed to the game reporter, which will handle
 * destruction and cleanup.
 */
uintptr_t slprs_game_report_create(const char *uid,
                                   const char *play_key,
                                   enum SlippiMatchmakingOnlinePlayMode online_mode,
                                   const char *match_id,
                                   uint32_t duration_frames,
                                   uint32_t game_index,
                                   uint32_t tie_break_index,
                                   int8_t winner_index,
                                   uint8_t game_end_method,
                                   int8_t lras_initiator,
                                   int32_t stage_id);

/**
 * Takes ownership of the `PlayerReport` at the specified pointer, adding it to the
 * `GameReport` at the corresponding pointer.
 */
void slprs_game_report_add_player_report(uintptr_t instance_ptr,
                                         uintptr_t player_report_instance_ptr);

/**
 * Calls through to `Jukebox::start_song`.
 */
void slprs_jukebox_start_song(uintptr_t exi_device_instance_ptr,
                              uint64_t hps_offset,
                              uintptr_t hps_length);

/**
 * Calls through to `Jukebox::stop_music`.
 */
void slprs_jukebox_stop_music(uintptr_t exi_device_instance_ptr);

/**
 * Calls through to `Jukebox::set_volume` with the Melee volume control.
 */
void slprs_jukebox_set_melee_music_volume(uintptr_t exi_device_instance_ptr, uint8_t volume);

/**
 * Calls through to `Jukebox::set_volume` with the DolphinSystem volume control.
 */
void slprs_jukebox_set_dolphin_system_volume(uintptr_t exi_device_instance_ptr, uint8_t volume);

/**
 * Calls through to `Jukebox::set_volume` with the DolphinMusic volume control.
 */
void slprs_jukebox_set_dolphin_music_volume(uintptr_t exi_device_instance_ptr, uint8_t volume);

/**
 * This should be called from the Dolphin LogManager initialization to ensure that
 * all logging needs on the Rust side are configured appropriately.
 *
 * For more information, consult `dolphin_logger::init`.
 *
 * Note that `logger_fn` cannot be type-aliased here, otherwise cbindgen will
 * mess up the header output. That said, the function type represents:
 *
 * ```
 * void Log(level, log_type, msg);
 * ```
 */
void slprs_logging_init(void (*logger_fn)(int, int, const char*));

/**
 * Registers a log container, which mirrors a Dolphin `LogContainer` (`RustLogContainer`).
 *
 * See `dolphin_logger::register_container` for more information.
 */
void slprs_logging_register_container(const char *kind,
                                      int log_type,
                                      bool is_enabled,
                                      int default_log_level);

/**
 * Updates the configuration for a registered logging container.
 *
 * For more information, see `dolphin_logger::update_container`.
 */
void slprs_logging_update_container(const char *kind, bool enabled, int level);

/**
 * Updates the configuration for registered logging container on mainline
 *
 * For more information, see `dolphin_logger::update_container`.
 */
void slprs_mainline_logging_update_log_level(int level);

/**
 * Starts a matchmaking session and returns its id. Any session already
 * running is cancelled first. Progress is polled with `slprs_mm_state`.
 */
uint64_t slprs_mm_start(uintptr_t exi_device_instance_ptr, struct SlippiMatchmakingRequest request);

/**
 * Current session state: 0 idle, 1 connecting, 2 queued, 3 matched, 4 failed.
 */
int slprs_mm_state(uintptr_t exi_device_instance_ptr);

/**
 * Once the state is matched, returns the match message exactly as the service
 * sent it, or null if it was already taken. Free with `slprs_mm_free_string`.
 */
char *slprs_mm_take_result_json(uintptr_t exi_device_instance_ptr);

/**
 * Once the state is failed, returns why. Free with `slprs_mm_free_string`.
 */
char *slprs_mm_error_message(uintptr_t exi_device_instance_ptr);

/**
 * Leaves the queue and ends the session with the given id. A stale id from an
 * earlier session is ignored so an old matchmaking object being torn down
 * cannot cancel a newer search.
 */
void slprs_mm_cancel(uintptr_t exi_device_instance_ptr, uint64_t session_id);

/**
 * Frees a string returned by another `slprs_mm_*` function.
 */
void slprs_mm_free_string(char *ptr);

/**
 * Writes a STUN binding request with a fresh transaction id into `out`, which
 * must have room for `SLPRS_STUN_REQUEST_LEN` bytes. Send it to a STUN server
 * from the netplay socket, then pass the reply to `slprs_stun_parse_response`.
 */
void slprs_stun_build_request(uint8_t *out);

/**
 * Reads the public IPv4 address and port out of a STUN reply to `request`
 * into `out`. Returns false, leaving `out` untouched, if the bytes are not a
 * success reply to that request.
 */
bool slprs_stun_parse_response(const uint8_t *request,
                               const uint8_t *response,
                               uintptr_t response_len,
                               struct SlippiStunObservation *out);

/**
 * Fetches the result of a recently played match via its ID.
 */
void slprs_fetch_match_result(uintptr_t exi_device_instance_ptr, const char *match_id);

/**
 * Gets the most recently fetched rank information of the user currently logged in.
 */
struct RustRankInfo slprs_get_rank_info(uintptr_t exi_device_instance_ptr);

/**
 * Instructs the `UserManager` on the EXI Device at the provided pointer to attempt
 * authentication. This runs synchronously on whatever thread it's called on.
 */
bool slprs_user_attempt_login(uintptr_t exi_device_instance_ptr);

/**
 * Instructs the `UserManager` on the EXI Device at the provided pointer to try to
 * open the login page in a system-provided browser view.
 */
void slprs_user_open_login_page(uintptr_t exi_device_instance_ptr);

/**
 * Instructs the `UserManager` on the EXI Device at the provided pointer to attempt
 * to initiate the older update flow.
 */
bool slprs_user_update_app(uintptr_t exi_device_instance_ptr);

/**
 * Instructs the `UserManager` on the EXI Device at the provided pointer to start watching
 * for the presence of a `user.json` file. The `UserManager` should have the requisite path
 * already from EXI device instantiation.
 */
void slprs_user_listen_for_login(uintptr_t exi_device_instance_ptr);

/**
 * Instructs the `UserManager` on the EXI Device at the provided pointer to sign the user out.
 * This will delete the `user.json` file from the underlying filesystem.
 */
void slprs_user_logout(uintptr_t exi_device_instance_ptr);

/**
 * Hooks through the `UserManager` on the EXI Device at the provided pointer to overwrite the
 * latest version field on the current user.
 */
void slprs_user_overwrite_latest_version(uintptr_t exi_device_instance_ptr, const char *version);

/**
 * Hooks through the `UserManager` on the EXI Device at the provided pointer to determine
 * authentication status.
 */
bool slprs_user_get_is_logged_in(uintptr_t exi_device_instance_ptr);

/**
 * Hooks through the `UserManager` on the EXI Device at the provided pointer to get information
 * for the current user. This then wraps it in a C struct to pass back so that ownership is safely
 * moved.
 *
 * This involves slightly more allocations than ideal, so this shouldn't be called in a hot path.
 * Over time this issue will not matter as once Matchmaking is moved to Rust we can share things
 * quite easily.
 */
struct RustUserInfo *slprs_user_get_info(uintptr_t exi_device_instance_ptr);

/**
 * Takes ownership back of a `UserInfo` struct and drops it.
 *
 * When the C/C++ side grabs `UserInfo`, it needs to ensure that it's passed back to Rust
 * to ensure that the memory layout matches - do _not_ call `free` on `UserInfo`, pass it here
 * instead.
 */
void slprs_user_free_info(struct RustUserInfo *ptr);

/**
 * Returns a C-compatible struct containing the chat message options for the current user.
 *
 * The return value of this _must_ be passed back to `slprs_user_free_messages` to free memory.
 */
struct RustChatMessages *slprs_user_get_messages(uintptr_t exi_device_instance_ptr);

/**
 * Returns a C-compatible struct containing the default chat message options.
 *
 * The return value of this _must_ be passed back to `slprs_user_free_messages` to free memory.
 */
struct RustChatMessages *slprs_user_get_default_messages(uintptr_t exi_device_instance_ptr);

/**
 * Takes back ownership of a `RustChatMessages` instance and frees the underlying data
 * by converting it into the proper Rust types.
 */
void slprs_user_free_messages(struct RustChatMessages *ptr);

/**
 * Passes along a direct code to add or update.
 */
void slprs_user_direct_codes_add_or_update(uintptr_t exi_device_instance_ptr,
                                           enum DirectCodeKind kind,
                                           const char *code);

/**
 * Gets the length of the current direct codes stack for the given `kind`.
 */
uint32_t slprs_user_direct_codes_get_length(uintptr_t exi_device_instance_ptr,
                                            enum DirectCodeKind kind);

/**
 * Checks to see if we have a direct code at `index`.
 *
 * This has the unfortunate aspect of going: Rust String -> CString -> C++ std::string, but
 * this will go away over time. Just be aware it's doing more allocations than is perhaps
 * ideal... but this area of code isn't performance sensitive anyway as it's not core
 * gameplay.
 */
char *slprs_user_direct_codes_get_code_at_index(uintptr_t exi_device_instance_ptr,
                                                enum DirectCodeKind kind,
                                                uintptr_t index);

/**
 * As the allocator on the C++ could be different, we need to provide a `free` method
 * that the C++ side will call when it's handled everything it needs to do.
 */
void slprs_user_direct_codes_free_code(char *code);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
